export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const GET_FORECAST_DATA = 'GET_FORECAST_DATA';
export const UPDATE_WEATHER_DATA = 'UPDATE_WEATHER_DATA';
export const ADD_FORECAST_DATA = 'ADD_FORECAST_DATA';
export const DELETE_FORECAST_DATA = 'DELETE_FORECAST_DATA';
